name: location_memo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.5
  # geolocator: ^10.1.0  # 一時的に無効化
  pdf: ^3.10.4
  printing: ^5.12.0
  file_picker: ^6.1.1
  image: ^4.1.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
