name: location_memo
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0-alpha+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  # geolocator: ^10.1.0  # 一時的に無効化
  pdf: ^3.11.3
  printing: ^5.14.0
  google_fonts: ^6.1.0
  file_picker: ^10.2.0
  image: ^4.5.4
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # フォント設定を追加
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
