name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
        
    - name: Check Flutter version
      run: flutter --version
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate code
      run: |
        echo "Cleaning build_runner..."
        flutter packages pub run build_runner clean
        echo "Building with build_runner..."
        flutter packages pub run build_runner build --delete-conflicting-outputs
        echo "Build runner completed"
      
    - name: Verify generated files
      run: |
        echo "Checking generated files..."
        ls -la lib/models/
        echo "Checking ai_service.dart..."
        ls -la lib/utils/ai_service.dart
        echo "Checking if .g.dart files exist..."
        find lib/models/ -name "*.g.dart" -type f
      
    - name: Build web
      run: flutter build web --release --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 